#!/usr/bin/env bash

# This basically acts like value++ for a given key, but modulo

if [ -z "$1" ]; then
  echo "ticktock: increment a value in the kv store, and reset it for a given modulo"
  echo "usage: ticktock <key> [modulo]"
  exit 1
fi

value="$(kvstok getkv "ticktock__$1")"
modulo="$2"
if [ -z "$modulo" ]; then
  modulo="$(kvstok getkv "ticktock__$1-modulo")"
fi
if
  [ -z "$modulo" ] || ! [ "$modulo" -eq "$modulo" ] 2>/dev/null
then
  modulo=2
fi
if [ -z "$value" ] || ! [ "$value" -eq "$value" ] 2>/dev/null; then
  value=0
fi
echo -n "$value"

# if the value + 1 is == modulo, then set to 0, otherwise set to value + 1

if [ "$((value + 1))" -eq "$modulo" ]; then
  kvstok addkv "ticktock__$1" 0
else
  kvstok addkv "ticktock__$1" "$((value + 1))"
fi

kvstok addkv "ticktock__$1-modulo" "$modulo"
